# Generated by Django 3.1.5 on 2021-01-24 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default=None, max_length=256)),
                ('date_made', models.DateTimeField(auto_now_add=True, verbose_name='data_utworzenia')),
                ('poziom_bezpieczenstwa', models.IntegerField(default=None)),
                ('metoda_testowania', models.IntegerField(default=None)),
                ('dostep_do_dokumentacji', models.BooleanField(default=False)),
                ('dostep_do_kodu', models.BooleanField(default=False)),
                ('dostep_do_mechanizmow_kryptograficznych', models.BooleanField(default=False)),
                ('dostep_do_dziennika_zdarzen', models.BooleanField(default=False)),
                ('tworzenie_kont', models.BooleanField(default=False)),
                ('mfa', models.BooleanField(default=False)),
                ('csp', models.BooleanField(default=False)),
                ('wprowadzanie_danych', models.BooleanField(default=False)),
                ('dzialanie_na_plikach', models.BooleanField(default=False)),
                ('wykorzystywany_mechanizm_zarzadzania_sesja', models.IntegerField(default=0)),
                ('wykorzystywany_kod', models.BooleanField(default=False)),
                ('wykorzystywane_uslugi_sieciowe', models.IntegerField(default=0)),
                ('klient', models.ForeignKey(blank=True, db_column='email', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pentester', models.ForeignKey(blank=True, db_column='username', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_name', models.CharField(default=None, max_length=100)),
                ('chapter_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asvstool.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(default=None, max_length=256)),
                ('nist', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('cwe', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('lvl1', models.BooleanField(default=True)),
                ('lvl2', models.BooleanField(default=True)),
                ('lvl3', models.BooleanField(default=True)),
                ('metoda_testowania', models.IntegerField(default=None)),
                ('dostep_do_dokumentacji', models.BooleanField(default=False)),
                ('dostep_do_kodu', models.BooleanField(default=False)),
                ('dostep_do_mechanizmow_kryptograficznych', models.BooleanField(default=False)),
                ('dostep_do_dziennika_zdarzen', models.BooleanField(default=False)),
                ('tworzenie_kont', models.BooleanField(default=False)),
                ('mfa', models.BooleanField(default=False)),
                ('csp', models.BooleanField(default=False)),
                ('wprowadzanie_danych', models.BooleanField(default=False)),
                ('dzialanie_na_plikach', models.BooleanField(default=False)),
                ('wykorzystywany_mechanizm_zarzadzania_sesja', models.IntegerField(default=0)),
                ('wykorzystywany_kod', models.BooleanField(default=False)),
                ('wykorzystywane_uslugi_sieciowe', models.IntegerField(default=0)),
                ('subsection_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asvstool.subsection')),
            ],
        ),
        migrations.CreateModel(
            name='ReqsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=256)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asvstool.project')),
                ('requirement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asvstool.requirement')),
            ],
            options={
                'unique_together': {('project', 'requirement')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.ManyToManyField(through='asvstool.ReqsProject', to='asvstool.Requirement'),
        ),
    ]
