# Generated by Django 3.1.5 on 2021-01-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asvstool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='metoda_testowania',
            new_name='Okres_poziom_bezpieczenstwa',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='csp',
            new_name='Okresl_dostep_do_dokumentacji',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='dostep_do_dokumentacji',
            new_name='Okresl_dostep_do_dziennika_zdarzen',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='dostep_do_dziennika_zdarzen',
            new_name='Okresl_dostep_do_kodu_zrodlowego',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='dostep_do_kodu',
            new_name='Okresl_dostep_do_mechanizmow_kryptograficznych',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='poziom_bezpieczenstwa',
            new_name='Okresl_metode_testowania',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='dostep_do_mechanizmow_kryptograficznych',
            new_name='Okresl_mozliwosc_dzialania_na_plikach',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='dzialanie_na_plikach',
            new_name='Okresl_mozliwosc_tworzenia_kont',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='mfa',
            new_name='Okresl_mozliwosc_wprowadzania_danych',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='wykorzystywane_uslugi_sieciowe',
            new_name='Okresl_wykorzystywane_uslugi_sieciowe',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tworzenie_kont',
            new_name='Okresl_wykorzystywany_kod',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='wykorzystywany_mechanizm_zarzadzania_sesja',
            new_name='Okresl_wykorzystywany_mechanizm_zarzadzania_sesja',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='wprowadzanie_danych',
            new_name='Okresl_zaimplementowanie_csp',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='wykorzystywany_kod',
            new_name='Okresl_zaimplementowanie_mfa',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pentester',
            new_name='Pentester',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia'),
        ),
    ]
