# Generated by Django 3.1.5 on 2021-01-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asvstool', '0002_auto_20210124_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Okres_poziom_bezpieczenstwa',
            new_name='Okresl_poziom_bezpieczenstwa',
        ),
    ]
