# Generated by Django 3.1.5 on 2021-01-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asvstool', '0006_auto_20210125_2045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('project_name', 'klient'), name='name of constraint'),
        ),
    ]
