# Generated by Django 3.1.5 on 2021-01-25 19:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asvstool', '0007_auto_20210125_2055'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='name of constraint',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('project_name', 'klient')},
        ),
    ]
