# Generated by Django 3.1.5 on 2021-01-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asvstool', '0008_auto_20210125_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='metoda_testowania',
        ),
        migrations.AddField(
            model_name='requirement',
            name='black_box',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='gray_box',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='white_box',
            field=models.BooleanField(default=True),
        ),
    ]
