# Generated by Django 3.1.5 on 2021-01-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asvstool', '0009_auto_20210128_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqsproject',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_name',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
