# Generated by Django 3.1.5 on 2021-01-31 22:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asvstool', '0012_auto_20210128_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='klient',
            new_name='Klient',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('project_name', 'Klient')},
        ),
    ]
